#include "register_types.cpp"
#include "simd_types.cpp"
#include "type_i32_4.cpp"
#include "type_f32_4.cpp"
#include "simd_f32.cpp"
#include "simd_i32.cpp"
#include "fastarray_2f32.cpp"
#include "fastarray_4f32.cpp"
#include "fastarray_4i32.cpp"
#include "vec4_i32.cpp"
#include "simd_cpu.cpp"

